// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp0HIAgQbW_vUsPWpEGLOtCFzP_hB4YbA',
    appId: '1:912680189228:web:3e09f977a5051b9e064089',
    messagingSenderId: '912680189228',
    projectId: 'flutterlistappkord',
    authDomain: 'flutterlistappkord.firebaseapp.com',
    storageBucket: 'flutterlistappkord.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptnPfFYOT3aBSt8VTxRfP86DDIlD7zkA',
    appId: '1:912680189228:android:348e3749800e7c95064089',
    messagingSenderId: '912680189228',
    projectId: 'flutterlistappkord',
    storageBucket: 'flutterlistappkord.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUPHdgqExHyGrkuXFAxO_mqNLwtGzQJ4',
    appId: '1:912680189228:ios:77fd698f04801bea064089',
    messagingSenderId: '912680189228',
    projectId: 'flutterlistappkord',
    storageBucket: 'flutterlistappkord.firebasestorage.app',
    iosBundleId: 'com.example.tasklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHUPHdgqExHyGrkuXFAxO_mqNLwtGzQJ4',
    appId: '1:912680189228:ios:77fd698f04801bea064089',
    messagingSenderId: '912680189228',
    projectId: 'flutterlistappkord',
    storageBucket: 'flutterlistappkord.firebasestorage.app',
    iosBundleId: 'com.example.tasklist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp0HIAgQbW_vUsPWpEGLOtCFzP_hB4YbA',
    appId: '1:912680189228:web:24aca4490c20e7d4064089',
    messagingSenderId: '912680189228',
    projectId: 'flutterlistappkord',
    authDomain: 'flutterlistappkord.firebaseapp.com',
    storageBucket: 'flutterlistappkord.firebasestorage.app',
  );

}